- job:
    name: ironic-staging-drivers-dsvm-all-drivers
    parent: legacy-dsvm-base
    run: playbooks/legacy/ironic-staging-drivers-dsvm-all-drivers/run.yaml
    post-run: playbooks/legacy/ironic-staging-drivers-dsvm-all-drivers/post.yaml
    timeout: 4800
    irrelevant-files:
      - ^test-requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^ironic-staging-drivers/tests/.*$
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/ironic
      - openstack/ironic-staging-drivers

- project:
    check:
      jobs:
        - ironic-staging-drivers-dsvm-all-drivers
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - ironic-staging-drivers-dsvm-all-drivers
        - openstack-tox-lower-constraints
