- job:
    name: ironic-staging-drivers-dsvm-all-drivers
    parent: legacy-dsvm-base
    run: playbooks/legacy/ironic-staging-drivers-dsvm-all-drivers/run.yaml
    post-run: playbooks/legacy/ironic-staging-drivers-dsvm-all-drivers/post.yaml
    timeout: 4800
    irrelevant-files:
      - ^test-requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^ironic-staging-drivers/tests/.*$
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/ironic
      - openstack/ironic-staging-drivers

- project:
    vars:
      rtd_webhook_id: '44747'
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-lower-constraints-jobs
      - docs-on-readthedocs
      - check-requirements
    check:
      jobs:
        - ironic-staging-drivers-dsvm-all-drivers
    gate:
      jobs:
        - ironic-staging-drivers-dsvm-all-drivers
