#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

SCRIPTDIR=$(dirname $0)

install -D -g root -o root -m 0755 ${SCRIPTDIR}/syslog-setup.sh /usr/bin/syslog-setup.sh

case "$DIB_INIT_SYSTEM" in
    systemd)
        install -D -g root -o root -m 0755 ${SCRIPTDIR}/syslog-setup.service /usr/lib/systemd/system/syslog-setup.service
        systemctl enable syslog-setup.service
        ;;
    *)
        echo "Unsupported init system"
        exit 1
        ;;
esac
