- hosts: conductor
  gather_facts: no
  tasks:
    - add_host:
        group: ironic
        hostname: "{{ item.name }}"
        ansible_ssh_host: "{{ item.ip }}"
        ansible_ssh_user: "{{ item.user }}"
        ironic_extra: "{{ item.extra | default({}) }}"
      with_items: "{{ ironic_nodes }}"
      tags: always
