---
- include: add-ironic-nodes.yaml

- hosts: ironic
  gather_facts: no
  roles:
    - role: wait
      tags: wait

- hosts: ironic
  name: Default cleaning playbook, wipes disk metadata and/or shreds disks
  roles:
    - clean
