---
- include: add-ironic-nodes.yaml

- hosts: ironic
  gather_facts: no
  roles:
    - role: wait
      tags: wait

- hosts: ironic
  roles:
    - discover
    - prepare
    - deploy
    - configure
  post_tasks:
    - name: flush disk state
      command: sync
