---
- include: add-ironic-nodes.yaml

- hosts: ironic
  gather_facts: no
  roles:
    - role: wait
      tags: wait

- hosts: ironic
  roles:
    - role: deploy
    - role: shutdown
      tags: shutdown
