- block:
  - name: download configdrive data
    get_url:
      url: "{{ configdrive }}"
      dest: /tmp/{{ inventory_hostname }}.cndrive
    async: 600
    poll: 15
    when: "{{ configdrive|default('') != 'file' }}"
  - block:
    - name: get configdrive dir
      command: dirname {{ inventory_file }}
      delegate_to: conductor
      register: config_dir
    - name: copy configdrive file to node
      copy:
        src: "{{ config_dir.stdout }}/{{ inventory_hostname }}.cndrive"
        dest: /tmp/{{ inventory_hostname }}.cndrive
    - name: remove configdrive from conductor
      command: rm -f {{ config_dir.stdout }}/{{ inventory_hostname }}.cndrive
      delegate_to: conductor
    when: "{{ configdrive|default('') == 'file' }}"
  - name: calculate configdrive size
    command: stat -c "%s" /tmp/{{ inventory_hostname }}.cndrive
    register: configdrive_size
  - name: store configdrive partition info for parted
    set_fact:
      configdrive_partition:
        - name: configdrive
          size_mib: configdrive_size.stdout
      all_partitions: "{{ ironic_partitions + configdrive_partition }}"
  when: configdrive is defined

- name: erase partition table
  become: yes
  command: dd if=/dev/zero of={{ ironic_root_device }} bs=512 count=36
  when: "{{ not preserve_ephemeral|default('no')|bool }}"

- name: run parted
  become: yes
  parted:
    device: "{{ ironic_root_device }}"
    dryrun: "{{ preserve_ephemeral|default('no')|bool }}"
    new_label: yes
    label: msdos
    partitions: "{{ all_partitions|default(ironic_partitions) }}"
  register: parts

- name: make swap
  become: yes
  command: mkswap -L swap1 {{ parts.created.swap }}
  when: "{{ parts.created.swap is defined }}"

- name: link to mkfs (irsible workaround)
  become: yes
  file:
    state: link
    src: /usr/local/sbin/mkfs
    dest: /sbin/mkfs

- name: format ephemeral partition
  become: yes
  command: mkfs -F -t {{ ephemeral_format }} -L ephemeral0 {{ parts.created.ephemeral }}
  when: "{{ parts.created.ephemeral is defined and not preserve_ephemeral|default('no')|bool }}"

- name: write configdrive
  become: yes
  command: dd if=/tmp/{{ inventory_hostname }}.cndrive of={{ configdrive_part }}
  when: configdrive is defined
