- block:
  - name: download configdrive data
    get_url:
      url: "{{ configdrive.location }}"
      dest: /tmp/{{ inventory_hostname }}.gz.base64
    async: 600
    poll: 15
    when: "{{ configdrive.type|default('') == 'url' }}"
  - block:
    - name: copy configdrive file to node
      copy:
        src: "{{ configdrive.location }}"
        dest: /tmp/{{ inventory_hostname }}.gz.base64
    - name: remove configdrive from conductor
      file:
        path: "{{ configdrive.location }}"
        state: absent
      delegate_to: conductor
    when: "{{ configdrive.type|default('') == 'file' }}"
  - name: unpack configdrive
    shell: cat /tmp/{{ inventory_hostname }}.gz.base64 | base64 --decode | gunzip > /tmp/{{ inventory_hostname }}.cndrive
  - name: calculate configdrive size
    command: stat -c "%s" /tmp/{{ inventory_hostname }}.cndrive
    register: configdrive_size
  - name: set configdrive partition and ceil its size in MiB
    set_fact:
      configdrive_partition:
        - name: configdrive
          size_mib: "{{ (configdrive_size.stdout|int / 1024 / 1024 +1)|int  }}"
  - set_fact:
      all_partitions: "{{ ironic_partitions + configdrive_partition }}"
  when: configdrive is defined

- name: erase partition table
  become: yes
  command: dd if=/dev/zero of={{ ironic_root_device }} bs=512 count=36
  when: "{{ not preserve_ephemeral|default('no')|bool }}"

- name: run parted
  become: yes
  parted:
    device: "{{ ironic_root_device }}"
    dryrun: "{{ preserve_ephemeral|default('no')|bool }}"
    new_label: yes
    label: msdos
    partitions: "{{ all_partitions|default(ironic_partitions) }}"
  register: parts

- name: reset image target to root partition
  set_fact:
    ironic_image_target: "{{ parts.created.root }}"

- name: make swap
  become: yes
  command: mkswap -L swap1 {{ parts.created.swap }}
  when: "{{ parts.created.swap is defined }}"

- name: format ephemeral partition
  become: yes
  command: mkfs -F -t {{ ephemeral_format }} -L ephemeral0 {{ parts.created.ephemeral }}
  when: "{{ parts.created.ephemeral is defined and not preserve_ephemeral|default('no')|bool }}"

- name: write configdrive
  become: yes
  command: dd if=/tmp/{{ inventory_hostname }}.cndrive of={{ parts.created.configdrive }}
  when: configdrive is defined
