- name: erase partition table
  become: yes
  command: dd if=/dev/zero of={{ ironic_root_device }} bs=512 count=36
  when: "{{ not preserve_ephemeral|default('no')|bool }}"

- name: run parted
  become: yes
  parted:
    device: "{{ ironic_root_device }}"
    dryrun: "{{ preserve_ephemeral|default('no')|bool }}"
    new_label: yes
    label: msdos
    partitions: "{{ ironic_partitions }}"
  register: parts

- name: reset image target to root partition
  set_fact:
    ironic_image_target: "{{ parts.created.root }}"

- name: make swap
  become: yes
  command: mkswap -L swap1 {{ parts.created.swap }}
  when: "{{ parts.created.swap is defined }}"

- name: format ephemeral partition
  become: yes
  command: mkfs -F -t {{ ephemeral_format }} -L ephemeral0 {{ parts.created.ephemeral }}
  when: "{{ parts.created.ephemeral is defined and not preserve_ephemeral|default('no')|bool }}"
