- block:
  - name: get devices wwn facts
    facts_wwn:
      devices: "{{ ansible_devices.keys() }}"
  - name: calculate root hint
    root_hints:
      root_device_hints: "{{ root_device_hints }}"
      ansible_devices: "{{ ansible_devices }}"
      ansible_devices_wwn: "{{ devices_wwn }}"
  when: root_device_hints is defined

- set_fact:
    ironic_root_device: /dev/{{ ansible_devices.keys()[0] }}
  when: (root_device_hints is undefined) or (ironic_root_device is undefined)
- set_fact:
    ironic_image_target: "{{ ironic_root_device }}"
