- name: erase partition table
  become: yes
  command: dd if=/dev/zero of={{ ironic_root_device }} bs=512 count=36
  when: "{{ not ironic.partition_info.preserve_ephemeral|default('no')|bool }}"

- name: run parted
  become: yes
  ironic_parted:
    device: "{{ ironic_root_device }}"
    label: "{{ ironic.partition_info.label }}"
    dry_run: "{{ ironic.partition_info.preserve_ephemeral|default('no')|bool }}"
    partitions: "{{ ironic.partition_info.partitions }}"
  register: parts

- name: reset image target to root partition
  set_fact:
    ironic_image_target: "/dev/{{ parts.created.root }}"

- name: make swap
  become: yes
  command: mkswap -L swap1 /dev/{{ parts.created.swap }}
  when: "{{ parts.created.swap is defined }}"

- name: format ephemeral partition
  become: yes
  filesystem:
    dev: "/dev/{{ parts.created.ephemeral }}"
    fstype: "{{ ironic.partition_info.ephemeral_format }}"
    force: yes
    opts: "-L ephemeral0"
  when: "{{ parts.created.ephemeral is defined and not ironic.partition_info.preserve_ephemeral|default('no')|bool }}"

- name: save block device for configdrive if partition was created
  set_fact:
    ironic_configdrive_target: "/dev/{{ parts.created.configdrive }}"
  when: "{{ parts.created.configdrive is defined }}"
